### ISSUE TITLE
Update system requirements for Docker for Windows to reflect that it's not supported where BitLocker is enforced

### ISSUE THREAD

**Issue by mikenri** [docker/docker.github.io#10242]
File: [docker-for-windows/install.md](https://docs.docker.com/docker-for-windows/install/)

Docker for Desktop does not work in environments where BitLocker is enforced on fixed drives by group policy.

It fails to start as reported by many users here:  https://github.com/docker/for-win/issues/1297

The system requirements should be updated to reflect that Docker For Desktop is not supported in business environments where BitLocker is enforced by Group Policy.

**Comment by lesterlitch** [comment]
This is a crippling issue. Can we at least get a comment from the docker team if this is going to be considered for a fix in a future release?

**Comment by prat0088** [comment]
I hit this as well.  WSL2 engine is a no-go for us due to BitLocker policy.

**Comment by sirdawidd** [comment]
It was detected 3 years ago, still nothing in this case, where all tickets are closed as resolved :/

**Comment by JanneRantala** [comment]
Unbelievable, after three years this issue still exists. I thought that one point someone from MS mentioned, that this issue is being investigated with the OS team (or some other, doesn't really matter). Doesn't Microsoft take Windows users seriously or what is taking so long with this?

**Comment by Pagni** [comment]
This is blocking Docker adoption in our organization.
Obviously it clashes with GDPR requirements. 

Please consider prioritizing. It's a major functionality issue (but now a place for my auditor pals to go hunt, so that's nice).

**Comment by revikor** [comment]
Any updates on this - are requirements going to be updated? It's supposedly fixed in Windows server but it looks like the fix never made it into Windows 10.

https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/530

**Comment by lesterlo** [comment]
Still no fix :(

**Comment by spmanjunath** [comment]
Is there a fix for the issue?  Updating registry is a hack, and not something that can be done in corporate environment.  Advise on how devs have worked around this problem will be helpful - it is difficult to believe this has been open this long.  The current constraint essential makes docker desktop unusable for Windows containers.  Thanks.

**Comment by JanneRantala** [comment]
No solution as far as I know. I'm using scheduled task to run registry hack, but GPO overrides that again when policies are synced. 

Yeah, pretty unbelievable that this is still an issue.

**Comment by benzbatman** [comment]
Thanks for nothing I guess?

For those looking for a workaround, here's what you can do with two GPOs deployed to your workstations:
![image](https://user-images.githubusercontent.com/50244937/185204023-e72f16b1-422c-4ff5-9cf1-0d573ec73a03.png)
![image](https://user-images.githubusercontent.com/50244937/185204438-80a830f5-166e-4c4b-a539-a04a96042f67.png)
